"""
reports.py
==========
The "My Progress" popup (bar chart of this session's results) and the
PDF report export using reportlab.
"""

import datetime
import os

import tkinter as tk
from tkinter import messagebox

import matplotlib
matplotlib.use("TkAgg")
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib import colors as pdf_colors
    from reportlab.pdfgen import canvas as pdf_canvas
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

from theme import COLOR_CARD, COLOR_TEXT, COLOR_MUTED, COLOR_PRIMARY, COLOR_ACCENT
from assessments import severity_color


def generate_pdf_report(user_name, records):
    """Generates a professional PDF report of the session's screening results."""
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError(
            "reportlab is not installed. Run: pip install reportlab --break-system-packages"
        )

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H%M%S")
    safe_name = "".join(c for c in user_name if c.isalnum() or c in (" ", "_")).strip() or "user"
    filename = f"MindCare_Report_{safe_name}_{timestamp}.pdf"

    c = pdf_canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    y = height - 25 * mm

    c.setFillColor(pdf_colors.HexColor("#0d1b2a"))
    c.rect(0, height - 30 * mm, width, 30 * mm, fill=True, stroke=False)
    c.setFillColor(pdf_colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(20 * mm, height - 18 * mm, "MindCare - Screening Report")
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, height - 26 * mm,
                 f"Prepared for: {user_name}   |   Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")

    y = height - 45 * mm
    c.setFillColor(pdf_colors.HexColor("#1e293b"))
    c.setFont("Helvetica-Bold", 13)
    c.drawString(20 * mm, y, "Summary of Results")
    y -= 10 * mm

    for r in records:
        c.setFillColor(pdf_colors.HexColor("#2a9df4"))
        c.setFont("Helvetica-Bold", 11)
        c.drawString(20 * mm, y, f"{r['name']}")
        c.setFillColor(pdf_colors.black)
        c.setFont("Helvetica", 10)
        c.drawString(70 * mm, y, f"Score: {r['score']} / {r['max']}  ({r['pct']}%)")
        y -= 6 * mm
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(20 * mm, y, r["interpretation"][:100])
        y -= 10 * mm
        if y < 40 * mm:
            c.showPage()
            y = height - 25 * mm

    y -= 5 * mm
    c.setFillColor(pdf_colors.HexColor("#64748b"))
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(20 * mm, y, "This report is generated by an educational screening tool and is")
    y -= 4 * mm
    c.drawString(20 * mm, y, "NOT a clinical diagnosis. Please consult a licensed mental health professional.")

    c.save()
    return os.path.abspath(filename)


class ProgressWindow(tk.Toplevel):
    def __init__(self, parent, records):
        super().__init__(parent)
        self.records = records
        self.user_name = getattr(parent, "user_name", "there")
        self.title("My Progress")
        self.geometry("560x640")
        self.minsize(560, 640)
        self.configure(bg=COLOR_CARD)

        tk.Label(self, text="📊 Your Screening Results This Session",
                 font=("Segoe UI", 13, "bold"), bg=COLOR_CARD, fg=COLOR_PRIMARY
                 ).pack(pady=(20, 10))

        names = [r["name"] for r in records]
        pcts = [r["pct"] for r in records]
        colors = [severity_color(p) for p in pcts]

        fig = Figure(figsize=(5, 3.3), dpi=100, facecolor=COLOR_CARD)
        ax = fig.add_subplot(111)
        ax.set_facecolor(COLOR_CARD)
        bars = ax.bar(names, pcts, color=colors)
        ax.set_ylim(0, 100)
        ax.set_ylabel("Severity (%)", color=COLOR_TEXT)
        ax.set_title("Lower is generally better (except Wellbeing)", color=COLOR_TEXT)
        ax.tick_params(colors=COLOR_TEXT)
        for spine in ax.spines.values():
            spine.set_color(COLOR_MUTED)
        for bar, pct in zip(bars, pcts):
            ax.text(bar.get_x() + bar.get_width() / 2, pct + 2, f"{pct}%",
                    ha="center", fontsize=9, color=COLOR_TEXT)

        canvas = FigureCanvasTkAgg(fig, master=self)
        canvas.draw()
        canvas.get_tk_widget().pack(padx=15, pady=5)

        detail_frame = tk.Frame(self, bg=COLOR_CARD)
        detail_frame.pack(fill="x", padx=20, pady=10)
        for r in records:
            tk.Label(
                detail_frame,
                text=f"• {r['name']}: {r['score']}/{r['max']} - {r['interpretation']}",
                font=("Segoe UI", 9), bg=COLOR_CARD, fg=COLOR_TEXT,
                wraplength=460, justify="left", anchor="w"
            ).pack(fill="x", pady=2)

        export_btn = tk.Button(
            self, text="📄 Export PDF Report", bg=COLOR_ACCENT, fg="white",
            font=("Segoe UI", 10, "bold"), relief="flat", padx=16, pady=10,
            cursor="hand2", command=self.export_pdf
        )
        export_btn.pack(pady=(5, 15))

    def export_pdf(self):
        try:
            path = generate_pdf_report(self.user_name, self.records)
            messagebox.showinfo("Report Saved", f"PDF report saved to:\n{path}")
        except Exception as e:
            messagebox.showerror("Export Failed", str(e))
